version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  lint:
    docker:
      - image: circleci/node:14.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - run: yarn lint
  test:
    docker:
      - image: circleci/node:14.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - run: yarn compile
      - run: yarn test
  coverage:
    docker:
      - image: circleci/node:14.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - run: yarn coverage
      - store_artifacts:
          path: coverage
  deploy-hardhat:
    docker:
      - image: circleci/node:14.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - run: yarn compile
      - run: yarn deploy:hardhat
  benchmark:
    docker:
      - image: circleci/node:14.6
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - run: yarn benchmark
workflows:
  version: 2
  build_lint_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      #- coverage:
          #requires:
            #- build
            #- test # only run if tests pass, redundantly runs tests
      - benchmark:
          requires:
            - build
      - deploy-hardhat:
          requires:
            - build
