name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Build
        run: yarn build

  test-solidity-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Compile
        run: yarn build
      - name: Test
        run: yarn workspace @balancer-labs/v2-solidity-utils test

  test-standalone-utils:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Compile
        run: yarn build
      - name: Test
        run: yarn workspace @balancer-labs/v2-standalone-utils test

  test-vault:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Compile
        run: yarn build
      - name: Test
        run: yarn workspace @balancer-labs/v2-vault test

  test-pools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Compile
        run: yarn build
      - name: Test
        run: yarn workspaces foreach --verbose --include @balancer-labs/v2-pool-* run test

  test-asset-managers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Compile
        run: yarn build
      - name: Test
        run: yarn workspaces foreach --verbose --include @balancer-labs/v2-asset-manager-* run test

  test-distributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Compile
        run: yarn build
      - name: Test
        run: yarn workspace @balancer-labs/v2-distributors test

  test-liquidity-mining:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Compile
        run: yarn build
      - name: Test
        run: yarn workspace @balancer-labs/v2-liquidity-mining test

  test-governance-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Compile
        run: yarn build
      - name: Test
        run: yarn workspace @balancer-labs/v2-governance-scripts test

  check-deployment-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Compile balancer-js
        run: yarn workspace @balancer-labs/balancer-js build
      - name: Check Deployment Artifacts
        run: yarn workspace @balancer-labs/v2-deployments check-artifacts

  check-deployment-addresses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Compile balancer-js
        run: yarn workspace @balancer-labs/balancer-js build
      - name: Prepare Config
        run: yarn workspace @balancer-labs/v2-deployments ci:prepare-config
        env:
          ALCHEMY_MAINNET_ARCHIVE_ENDPOINT: ${{ secrets.ALCHEMY_MAINNET_ARCHIVE_ENDPOINT }}
          ALCHEMY_POLYGON_ARCHIVE_ENDPOINT: ${{ secrets.ALCHEMY_POLYGON_ARCHIVE_ENDPOINT }}
          ALCHEMY_ARBITRUM_ARCHIVE_ENDPOINT: ${{ secrets.ALCHEMY_ARBITRUM_ARCHIVE_ENDPOINT }}
          ALCHEMY_OPTIMISM_ARCHIVE_ENDPOINT: ${{ secrets.ALCHEMY_OPTIMISM_ARCHIVE_ENDPOINT }}
      - name: Check Deployment Addresses
        run: yarn workspace @balancer-labs/v2-deployments check-deployments

  check-action-ids:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Compile balancer-js
        run: yarn workspace @balancer-labs/balancer-js build
      - name: Prepare Config
        run: yarn workspace @balancer-labs/v2-deployments ci:prepare-config
        env:
          ALCHEMY_MAINNET_ARCHIVE_ENDPOINT: ${{ secrets.ALCHEMY_MAINNET_ARCHIVE_ENDPOINT }}
          ALCHEMY_POLYGON_ARCHIVE_ENDPOINT: ${{ secrets.ALCHEMY_POLYGON_ARCHIVE_ENDPOINT }}
          ALCHEMY_ARBITRUM_ARCHIVE_ENDPOINT: ${{ secrets.ALCHEMY_ARBITRUM_ARCHIVE_ENDPOINT }}
          ALCHEMY_OPTIMISM_ARCHIVE_ENDPOINT: ${{ secrets.ALCHEMY_OPTIMISM_ARCHIVE_ENDPOINT }}
      - name: Check Action IDs
        run: yarn workspace @balancer-labs/v2-deployments check-action-ids

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: '**/node_modules'
          key: yarn-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install
        run: yarn --immutable
        if: steps.cache.outputs.cache-hit != 'true'
      - name: Compile
        run: yarn build
      - name: Benchmark
        run: yarn workspace @balancer-labs/v2-benchmarks benchmark

env:
  CI: true
